### ISSUE TITLE
Documentation - Branch Metrics links 404

### ISSUE THREAD

**Issue by quentin41500** [mParticle/mparticle-android-sdk#10]
Hey guys,

The link `https://github.com/mparticle-integrations/mparticle-android-integration-branchmetrics` is not working when clicking on the link for branch metrics, should be `https://github.com/mparticle-integrations/mparticle-android-integration-branch` instead.

Thanks

**Comment by quentin41500** [comment]
PR #11 Opened

**Comment by samdozor** [comment]
PR accepted, thank again!
