### ISSUE TITLE
Cannot show push notification from Braze

### ISSUE THREAD

**Issue by samuelcai-chancetop** [mParticle/mparticle-android-sdk#157]
Our app uses mParticle and Braze, and it's configured based on [this document](https://github.com/mparticle-integrations/mparticle-android-integration-appboy) to handle push notification from Braze.

Recently I updated our app's com.mparticle:android-core from 5.23.0 to 5.37.0, also changed our app to target sdk version 31 (previous is 30).
But I found that our app could not show push notification from Braze anymore (our app has com.mparticle:android-appboy-kit:5.37.0)

I turned on mParticle verbose log, based on the log, looked like the Braze kit's onMessageRecieved was not called after push notification arrived (see method generateCloudMessage in MPServiceUtil.java).

After digging more source codes of 5.37.0 and latest 5.40.2, and by comparing previous 5.23.0, I think the root cause is that kitsLoadedListener is not called after push notification arrived.
In 5.23.0 line 169 in MPServiceUtil.java, there is a line in method generateCloudMessage, which is missing in 5.37.0 and 5.40.2:
`KitFrameworkWrapper.addKitsLoadedListener(kitsLoadedListener);`, it calls `listener.onKitsLoaded()` if kitsLoaded.
The following `MParticle.start()` does nothing because MParticle instance is not null.

**Comment by willpassidomo** [comment]
@samuelcai-chancetop Hey, I see exactly what you're talking about, and I think your assessment is spot on. I'm going to try to put a fix up for this today, just working on adding some testing so we don't run into this issue again. I appreciate you making this a layup!

**Comment by samuelcai-chancetop** [comment]
Close as this has been fixed in 5.41.1 https://github.com/mParticle/mparticle-android-sdk/pull/178
