### ISSUE TITLE
com.mparticle:android-leanplum-kit dependency is blocking from migrating to java8

### ISSUE THREAD

**Issue by atoropov** [mParticle/mparticle-android-sdk#17]
Latest Android Studio (3.0+) allows to use java8 features (https://developer.android.com/studio/write/java8-support.html). But seems like com.mparticle:android-leanplum-kit dependency is blocking us from migrating.

We see this error when trying to build an apk:
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@...\app\build\intermediates\tmp\desugar_args6686230356983584219}

Without the dependency it works fine. Unfortunately logs (even debug ones) doesn't show specific reason.

**Comment by samdozor** [comment]
This is an issue with the latest Leanplum SDK. Closing the issue here.

Please see:
https://github.com/Leanplum/Leanplum-Android-SDK/issues/113
