### ISSUE TITLE
Leanplum not started when using logPushRegistration

### ISSUE THREAD

**Issue by akvashi** [mParticle/mparticle-android-sdk#18]
Issue seems to only occur on Samsung S7 Edge with Android 6.0

Leanplum setGCMSenderID is never called when calling logPushRegistration. 

Same code works fine when using 8.0 on Pixel 2.

Will add more info here as I test other phones and Android Versions

**Comment by samdozor** [comment]
@akvashi were you ever able to reproduce this reliably? Also of note is that we've updated our Leanplum integration to their latest SDK which defaults to FCM, and it's strongly encouraged by Google and Leanplum to move to FCM.  Thanks!
