### ISSUE TITLE
Getting error when identifying

### ISSUE THREAD

**Issue by sbaar** [mParticle/mparticle-android-sdk#24]
When using any Identity api request during or after sdk initialization, I get the error
"Your mParticle workspace is not provisioned for Identity Sync. Please contact mParticle support for more information." Now that Identity is required, I don't know what this error means or how to resolve it.

No one has responded to my get in contact form on the website.

The effect of this error seems to be that no event is appears in my dashboard live stream, although events are propagating downstream to outputs fortunately.

**Comment by samdozor** [comment]
hey @sbaar can you shoot an email to support@mparticle.com so we can get you routed to our tech services/customer solutions team? This error indicates that your app key and secret is not provisioned for our IDSync API yet and is intentional. Thanks!

**Comment by samdozor** [comment]
@sbaar you should be hearing from our support soon. Provisioning for IDSync (and therefore SDK v5) requires some setup on our side per your team's Identity requirements. Once that setup is complete, this error should go away. Note that you *cannot* launch the app with the latest SDK until that has been completed.
