### ISSUE TITLE
Upgrade to appboy kit 2.2.5 in 4.x branch

### ISSUE THREAD

**Issue by veerenmandalia** [mParticle/mparticle-android-sdk#25]
I reported an [appboy crash[(https://github.com/Appboy/appboy-android-sdk/issues/101) to Braze. Braze mentions that this is fixed in appboy 2.2.5.

Could you bump up appboy to 2.2.5 for `com.mparticle:android-appboy-kit` in the 4.x branch to solve these crashes?

**Comment by samdozor** [comment]
hey @veerenmandalia - sure we can do that. You can also ignore our dependency and use 2.2.5 directly if you don't want to wait:


```
//example build.gradle
compile('com.mparticle:android-appboy-kit:4.17.12') {
        exclude group: 'com.appboy'
}
compile 'com.appboy:android-sdk-ui:2.2.5' 
```

**Comment by veerenmandalia** [comment]
@samdozor Thanks Sam!

Are there any downsides in doing this?

**Comment by samdozor** [comment]
@veerenmandalia nope! I would say if you're changing a major version like, say if Braze were to release version 3.0, then I would not recommend doing this. But as this is just a minor bugfix release, it should be safe enough.

**Comment by samdozor** [comment]
@veerenmandalia assuming you're all set here by now - please reach out to your mParticle solutions team member if you still need assistance.
