### ISSUE TITLE
You have different SharedPrefs which causes erroneous behavior

### ISSUE THREAD

**Issue by cihadturhan** [mParticle/mparticle-android-sdk#26]
1. Call `MParticle.getInstance().Messaging().enablePushNotifications("XXXXX");`
2. Observe `MParticle.getInstance().getConfigManager().isPushEnabled() == true`
3. Call `MParticle.getInstance().Messaging().disablePushNotifications();`
4. Observe `MParticle.getInstance().getConfigManager().isPushEnabled() == false` **but** it's still `true`

I think it's because you have different shared prefs file in [ConfigManager.java](https://github.com/mParticle/mparticle-android-sdk/blob/master/android-core/src/main/java/com/mparticle/internal/ConfigManager.java#L155) and in [PushRegistrationHelper.java](https://github.com/mParticle/mparticle-android-sdk/blob/master/android-core/src/main/java/com/mparticle/internal/PushRegistrationHelper.java#L30)
so it doesn't read what it wrote vice versa.

Please let me know if I'm wrong. 
Thanks

**Comment by samdozor** [comment]
hey @cihadturhan I believe you're correct - though the impact of this is restricted to that boolean value. 

The device will be properly registered and unregistered for push notifications after calling those respective APIs. You can also safely call `enablePushNotifications` multiple times without checking `isPushEnabled()`. Truth be told that boolean probably doesn't need to be exposed publicly.

We can get the boolean addressed in the next SDK release. Thanks for the report!

**Comment by samdozor** [comment]
Hi @cihadturhan! This should be resolved as of SDK 5.7.5. Thanks!
