### ISSUE TITLE
Support for automatic push registration via non-default FCM project in a multi-project app

### ISSUE THREAD

**Issue by veerenmandalia** [mParticle/mparticle-android-sdk#32]
I have an app which consumes Firebase push from multiple Firebase projects and follows [Firebase Multiproject Configuration](https://firebase.google.com/docs/projects/multiprojects).

mParticle push notifications configuration [[docs](https://docs.mparticle.com/developers/sdk/android/push-notifications)]: https://github.com/mParticle/mparticle-android-sdk/blob/6971da29ccefabad1913312b6c3b9bb00b0083a9/android-core/src/main/java/com/mparticle/messaging/MPMessagingAPI.java#L58 
senderId is ignored when FCM is used: https://github.com/mParticle/mparticle-android-sdk/blob/6971da29ccefabad1913312b6c3b9bb00b0083a9/android-core/src/main/java/com/mparticle/internal/PushRegistrationHelper.java#L35

Can this be updated so we can specify what project to use for mParticle?

A workaround is to have the base configuration for the app use the mParticle Firebase Project. But this means that Firebase Analytics will only go to mParticle Firebase Project. [link](https://firebase.google.com/docs/projects/multiprojects#use_multiple_projects_in_your_application). 
> Note: On Android and iOS, Analytics are only logged for the default app.

It also goes again the best practice mentioned [link](https://firebase.google.com/docs/projects/multiprojects#reliable-analytics)
> Ensure reliable reporting for Analytics
> For this reason, we recommend using the default configuration methods wherever possible.

**Comment by samdozor** [comment]
Hi @veerenmandalia! The way that this can be supported today is if you just pass the instance ID into our SDK for whichever project you'd like via this API [documented here](https://docs.mparticle.com/developers/sdk/android/push-notifications/#option-2---use-your-own-push-instance-id-service)

```
MParticle.getInstance().logPushRegistration(instanceID, senderId)
```

FCM keeps a map of `FirebaseInstanceId` objects, which are keyed on "application ID" by default, but seems like you can actually store them in the map as anything (the docs you linked use "secondary" as an example). That means in those cases you would have to pass in whichever key/tag you used.  We can investigate treating the sender ID passed in as the FCM application ID/tag. Alternatively we may have to introduce a new API for it completely to ensure backwards compatibility.

**Comment by veerenmandalia** [comment]
@samdozor Thanks for the info. So `instanceID` in `logPushRegistration(instanceID, senderId)` is the token and not a [FirebaseInstanceId](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId), correct?

**Comment by samdozor** [comment]
hey @veerenmandalia I believe they're the same thing? Token is the old terminology, instance ID is the new, until Google changes it again!

As it happens - we've actually pushed an update which I believe resolves your issue. We updated the version of the Firebase instance ID API we were using, and we're not requesting instance ID's specific to a sender/project ID: https://github.com/mParticle/mparticle-android-sdk/blob/master/android-core/src/main/java/com/mparticle/internal/PushRegistrationHelper.java#L35

I believe this should resolve your issue but please reopen if not.
