### ISSUE TITLE
IdentityApiResult.getUser is maked @NonNull, but it returns null

### ISSUE THREAD

**Issue by afedorychak** [mParticle/mparticle-android-sdk#34]
We sometimes get crashes because `IdentityApiResult` we receive in `TaskSuccessListener.onSuccess` has null user though it shouldn't, right?

This is how we create the task (kotlin):

              .identifyTask(
                BaseIdentityTask()
                  .addFailureListener { Timber.e("Identify Error: %s", it) }
                  .addSuccessListener { userIdentified(application, it.user) }
              )

**Comment by willpassidomo** [comment]
@afedorychak thank you for submitting the issue. We added additional logic to ensure that the `MParticleUser` returned in the `IdentityApiResponse` object is never null, regardless of state. These changes are available in version `5.10.1`
