### ISSUE TITLE
StrictMode warning(s) - slows app load beyond what Google expects/wants

### ISSUE THREAD

**Issue by chad-cmb** [mParticle/mparticle-android-sdk#345]
Here in example:
 08:58:00.697 18373 18373 D StrictMode: StrictMode policy violation; ~duration=448 ms: android.os.strictmode.DiskReadViolation
 08:58:00.697 18373 18373 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1199)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1000)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:145)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:238)
 08:58:00.697 18373 18373 D StrictMode: 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.s0.a(SourceFile:19)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.d0.b(SourceFile:15)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.d0.a(SourceFile:365)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.internal.j.a(SourceFile:296)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.identity.b.b(SourceFile:1)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.identity.c.getUserAttributes(SourceFile:1)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.kits.KitIntegration.getAllUserAttributes(KitIntegration.java:142)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.kits.LeanplumKit.onKitCreate(LeanplumKit.kt:52)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.kits.KitManagerImpl.initializeKit(KitManagerImpl.java:266)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:226)
 08:58:00.697 18373 18373 D StrictMode: 	at com.mparticle.kits.KitManagerImpl.lambda$updateKits$0$com-mparticle-kits-KitManagerImpl(KitManagerImpl.java:157)

Here is all the accumulative strict modes when we launch - it really adds up to a lot of time (especially considering we have of SDKs with the same problem):

StrictMode: StrictMode policy violation; ~duration=238 ms: android.os.strictmode.DiskReadViolation
StrictMode: StrictMode policy violation; ~duration=237 ms: android.os.strictmode.DiskReadViolation
StrictMode: StrictMode policy violation; ~duration=197 ms: android.os.strictmode.DiskReadViolation
StrictMode: StrictMode policy violation; ~duration=196 ms: android.os.strictmode.DiskReadViolation

**Comment by samdozor** [comment]
This was an issue in the Leanplum kit and was resolved here: https://github.com/mparticle-integrations/mparticle-android-integration-leanplum/commit/2fb8c71e6c5ba4afbf51115db5b948e7ece51981

And that was released as v5.51.0: https://github.com/mParticle/mparticle-android-sdk/commit/03289e14e72b87f1e57b192152ad1dfcc1bf8608
