### ISSUE TITLE
Push notifications are not working

### ISSUE THREAD

**Issue by gdziubinski** [mParticle/mparticle-android-sdk#35]
**PROBLEM**
Push Notifications does not work when we use any firebase version starting from `18.0.0`.

**REASON**
 The `FirebaseInstanceIdService` class got dropped (deprecated earlier here
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService).

The `mParticle` code has: 

```
public void enablePushNotifications(@NonNull String senderId) {
        MParticle.getInstance().Internal().getConfigManager().setPushSenderId(senderId);
        if (!MPUtility.isFirebaseAvailable()) {
            Logger.error("Push is enabled but Firebase Cloud Messaging library not found - you must add com.google.firebase:firebase-messaging:7.5 or later to your application.");
        }
        // ...
        else {
            PushRegistrationHelper.requestInstanceId(mContext, senderId);
        }
    }

```
and then
```
public static Boolean isFirebaseAvailable() {
        try {
            Class.forName("com.google.firebase.iid.FirebaseInstanceIdService");
            return true;
        }
        catch (Exception ignore) { }
        return false;
    }
```

The class does not exist. 

**SOLUTION**
The workaround is to use a dummy created class:
```
package com.google.firebase.iid

class FirebaseInstanceIdService
```
but long term `MPUtility#isFirebaseAvailable` should be updated.

**Comment by willpassidomo** [comment]
Hey @gdziubinski 
Thanks so much for bringing this to our attention. We have released a fix for this in our latest version, `5.10.0`
