### ISSUE TITLE
Please provide more meaningful changelogs

### ISSUE THREAD

**Issue by GrahamBorland** [mParticle/mparticle-android-sdk#376]
This is what the last few changelog entries look like:

<img width="409" alt="CleanShot 2023-05-06 at 11 11 51@2x" src="https://user-images.githubusercontent.com/5768767/236618024-32a4e2fe-7740-44d1-b5b2-a44b1f3e5758.png">

This tells us nothing about what's actually changed. Could you please update the changelog entries to be more useful? Thanks!

**Comment by samdozor** [comment]
You're completely right - and we will do this moving forward. Today our auto-rollup of commit messages only includes the commit messages for changes to the core SDK. The releases you linked above indeed had zero changes to the core SDK, but we can roll up changes from the kits in the changelog as well.
