### ISSUE TITLE
Breaking change in 5.50.4 (missing Appboy constants) 

### ISSUE THREAD

**Issue by GrahamBorland** [mParticle/mparticle-android-sdk#377]
Updating from 5.50.3 to 5.50.4:

```
> Task :libraries:analytics-mparticle:compileReleaseKotlin FAILED
e: file:///bitrise/src/libraries/analytics-mparticle/src/main/java/ynab/analytics/MParticleAnalytics.kt:11:12 Unresolved reference: appboy
e: file:///bitrise/src/libraries/analytics-mparticle/src/main/java/ynab/analytics/MParticleAnalytics.kt:158:47 Unresolved reference: Constants
```

The `com.appboy.Constants` import is no longer available.

**Comment by GrahamBorland** [comment]
It looks like it may have been renamed from `Constants.APPBOY` to `Constants.BRAZE`? This kind of breaking change needs a major version bump, not a patch bump.

**Comment by samdozor** [comment]
@GrahamBorland apologies for this. We generally do not do a major version rev for every respective SDKs major versions revs, as most customers to not make direct calls to partner SDK packages. That said - this should have at least been a minor version rev and included in release notes.
