### ISSUE TITLE
`IdentityStateListener` example out of date in docs

### ISSUE THREAD

**Issue by mateot1** [mParticle/mparticle-android-sdk#38]
Just noticed a small but potentially confusing discrepancy in the docs from the current api: https://docs.mparticle.com/developers/sdk/android/users/#listener - there are two `MParticleUser` params in the current version: https://github.com/mParticle/mparticle-android-sdk/blob/46eb14e6b24c28783326c66b3045ee1a726f33e6/android-core/src/main/java/com/mparticle/identity/IdentityStateListener.java#L14-L16

**Comment by willpassidomo** [comment]
Thanks @mateot1, we appreciate the report! This has been updated
