### ISSUE TITLE
MParticleTask<IdentityApiResult> incorrect order of onSuccess callbacks

### ISSUE THREAD

**Issue by jacekkrasowski** [mParticle/mparticle-android-sdk#39]
IdentityApiRequest attributes proceeded after onSuccess for TaskSuccessListener list

Example:

`MParticle.getInstance()?.Identity()?.login(
createIdentifyRequestFor(userInfoProvider.provideUser()))?
.addSuccessListener {
               it.assignUserAttributes()
sendSampleEvent()
            }`

in this example assignUserAttributes and sendSampleEvent get invoked before updating customerID declared in IdentityApiRequest past to `login`

Because of the issue, values are not overridden before actions on onSuccess are invoked, that takes us to the issue that messages related to given events have outdated values

**Comment by samdozor** [comment]
Hi @jacekkrasowski - I've tried to reproduce your issue but have no been able to. With the following example code, given a random UUID for customer ID, after every login() I see an upload with:
- an upload for the new MPID
- in that upload, the same UUID as a user identity
- in that upload, the same UUID as a user attribute
- in that upload, the same UUID as an event attribute

```java
MParticle.getInstance().Identity().login(
        IdentityApiRequest.withEmptyUser().customerId(UUID.randomUUID().toString()).build()
)
.addSuccessListener(new TaskSuccessListener() {
    @Override
    public void onSuccess(@NonNull IdentityApiResult identityApiResult) {
        String customerId = identityApiResult.getUser().getUserIdentities().get(MParticle.IdentityType.CustomerId);
        identityApiResult.getUser().setUserAttribute("customer-id", customerId);
        Map<String, String> map = new HashMap<>();
        map.put("customer-id", customerId);
        MParticle.getInstance().logEvent(new MPEvent.Builder("example event").customAttributes(map).build());
    }
});
```

Can you provide any more details? I'd also suggest reaching out directly to support@mparticle.com such that they can investigate with you.

**Comment by jacekkrasowski** [comment]
I am checking the mParticle console and automatic Android  messages tells me some bulk information about the events

![image](https://user-images.githubusercontent.com/13310962/67011704-68a56d80-f0f0-11e9-8876-4d3aa3f8536f.png)

it has customerID from previous session
It updates after few seconds to new one

**Comment by jacekkrasowski** [comment]
but you're right that callbacks order look correct, console says the same when looking at the timestamp.
Question is why do I see old customerID when new one is there

**Comment by jacekkrasowski** [comment]
Looks like issue got fixed itself, events started coming in correct order, from Monday 22th Oct
