### ISSUE TITLE
Detected Application Not Responding

### ISSUE THREAD

**Issue by dfpalomar** [mParticle/mparticle-android-sdk#44]
Hello guys. In our project we have recently detected in production an error produced by mParticle. It looks like a class is doing too much work on the UI thread. Please find below the details:

> Caused by com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
>        at org.json.JSONObject.numberToString(JSONObject.java:735)
>        at org.json.JSONStringer.value(JSONStringer.java:249)
>        at org.json.JSONArray.writeTo(JSONArray.java:613)
>        at org.json.JSONArray.toString(JSONArray.java:585)
>        **at com.mparticle.internal.aa.a(SourceFile:379)**
>        at com.mparticle.internal.aa.a(SourceFile:371)
>        at com.mparticle.internal.aa.g(SourceFile:344)
>        at com.mparticle.internal.aa.<init>(SourceFile:79)
>        at com.mparticle.internal.aa.b(SourceFile:69)
>        at com.mparticle.internal.f.a(SourceFile:159)
>        at com.mparticle.commerce.Cart.<init>(SourceFile:57)
>        at com.mparticle.identity.d.<init>(SourceFile:29)
>        at com.mparticle.identity.d.a(SourceFile:36)
>        at com.mparticle.identity.IdentityApi.getCurrentUser(SourceFile:79)
>        at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:160)
>        at com.mparticle.kits.KitManagerImpl$UpdateKitRunnable.run(KitManagerImpl.java:139)
>        at android.os.Handler.handleCallback(Handler.java:907)
>        at android.os.Handler.dispatchMessage(Handler.java:105)
>        at android.os.Looper.loop(Looper.java:216)
>        at android.app.ActivityThread.main(ActivityThread.java:7625)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Device:** HUAWEI Y9 2018
**Android Version:** 9

Our dependencies are:

com.mparticle:android-core:5.13.1
com.mparticle:android-adjust-kit:5.13.1
com.mparticle:android-appboy-kit:5.13.1

Since the code of the library is obfuscated we have no way to see what the problem is. The readme file of the project make reference to the version **5.13.3** but there is not a change log available from version 5.13.1.

Can you guys please have a look at this and let us know if the new versions fix the issue. Thanks in advance.

**Comment by willpassidomo** [comment]
Hey @dfpalomar, I'm sorry to hear you're having this issue. This looks like the `Cart` is having issues serializing to JSON in a timely manner, likely due to a large number of products in the users' `Cart`. Currently, the code that is causing the problem is deprecated even though we still use the API internally. It is slated to be removed completely in our next release

**Comment by willpassidomo** [comment]
Remove `Cart` class, both for public and internal usage in version `5.14.0`
