### ISSUE TITLE
Build warning for android-core

### ISSUE THREAD

**Issue by jchristof** [mParticle/mparticle-android-sdk#46]
Noticed the following build warning:

WARNING: [Processor] Library '/home/jonmartin/.gradle/caches/modules-2/files-2.1/com.mparticle/android-core/5.14.3/b4d68866f3348461e1dbd55956bc151e97e0236b/android-core-5.14.3.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/Nullable'
 Example of support library reference: 'android/support/annotation/Nullable'

Please advise.

**Comment by willpassidomo** [comment]
@jchristof Good catch! Thanks for pointing that out, it looks like we accidentally used the AndroidX `Nullable` annotation in a couple of places. I replaced them and this should be fixed next release

**Comment by willpassidomo** [comment]
fixed in version `5.14.4`
