### ISSUE TITLE
Remove legacy support dependency from Appboy kit

### ISSUE THREAD

**Issue by GrahamBorland** [mParticle/mparticle-android-sdk#51]
I'm using the [can-i-drop-jetifier Gradle plugin](https://github.com/plnice/can-i-drop-jetifier) to identify dependencies which still depend on the legacy Android support libraries instead of AndroidX.

It is telling me that the mParticle Appboy kit is still using the old support libraries.

```
Cannot drop Jetifier due to following external dependencies:

* com.mparticle:android-appboy-kit:5.14.5
```

We've been on AndroidX for two years now, so it would be good if the mParticle SDK could be brought up-to-date. Thanks.

The [Braze Android SDK documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#step-1-integrate-the-braze-library) does point out that they provide an AndroidX (pre-jetified) version of their SDK.

```
implementation "com.appboy:android-sdk-ui-jetified:+"
```

**Comment by willpassidomo** [comment]
@GrahamBorland I just tested the jetified library and it is compatible with our Appboy (Braze) kit implementation, so you are able to exclude our existing appboy dependency and replace it with the jetified version

You should update you `dependencies` block to include:

```
implementation('com.mparticle:appboy-kit:5.14.7') {
        exclude group: 'com.appboy', module: 'android-sdk-ui'
    }
    implementation 'com.appboy:android-sdk-ui-jetified:8.1.0'
```

I'm sorry you ran into this issue. We are constantly trying to monitor which build tools our customers are using and how we can help keep development as seamless as possible. We still have a number of customers who are not using AndroidX, although that is changing quickly, so in the end, we have to go with a dependency that isn't perfect for some. I expect this to get better for developers like you, who are up to date on the latest tools, in the near future
