### ISSUE TITLE
migrate to AndroidX from support lib

### ISSUE THREAD

**Issue by brianPlummer** [mParticle/mparticle-android-sdk#55]
We aren't able to turn off jetifier due to `com.mparticle:android-appboy-kit:5.14.10` and `com.mparticle:android-appsflyer-kit:5.14.10` use of support libraries.  Please consider migrating to androidX.  

Check out this great [article](https://adambennett.dev/2020/08/disabling-jetifier/)

**Comment by GrahamBorland** [comment]
Looks like a duplicate of #51

**Comment by willpassidomo** [comment]
Apologies for the wait. AndroidX support as of [v5.15.0](https://github.com/mParticle/mparticle-android-sdk/releases/tag/v5.15.0)
