### ISSUE TITLE
mParticle google analytics firebase integration

### ISSUE THREAD

**Issue by jzeferino** [mParticle/mparticle-android-sdk#58]
I already have the mParticle setup done and working. we can see our app events in the mParticle.

I want to integrate the google analytics firebase and I followed the [documentation](https://github.com/mparticle-integrations/mparticle-android-integration-google-analytics-firebase).

I also added the integration the mParticle website.

I can see the log "Google Analytics for Firebase detected" but I don't see any custom event on the firebase. 
I can only see the default events like `accept_language` or `accept_language`

One thing that I also tried was to get the kit programmatically, but I always got `null`
`MParticle.getInstance()?.getKitInstance(MParticle.ServiceProviders.GOOGLE_ANALYTICS_FIREBASE)`

![Screenshot 2020-11-05 at 16 25 55](https://user-images.githubusercontent.com/10722952/98268149-1564be00-1f84-11eb-9955-0fa7457e2f9b.png)

Note: We are using version 5.15.0

Can you guys please point some directions?

**Comment by jzeferino** [comment]
cc @willpassidomo

**Comment by samdozor** [comment]
hey @jzeferino! Can you confirm that you have:

1. Added the Firebase configuration AND the Firebase connection for Android at app.mparticle.com
2. Enabled the connection for development/product mode (whichever mode the SDK is running in)?

**Comment by jzeferino** [comment]
hey @samdozor, I confirm I have both configured.

**Comment by samdozor** [comment]
Thanks for confirming - can you shoot a note to support@mparticle.com and the team will take a look at your setup?

**Comment by jzeferino** [comment]
I will do it. thank you @samdozor

**Comment by jzeferino** [comment]
This was a wrong configuration we had in the mParticle integration with Google Analytics for Firebase in the portal.
