### ISSUE TITLE
Appboy Kit still uses legacy android support dependency 

### ISSUE THREAD

**Issue by brian-plummer-okcupid** [mParticle/mparticle-android-sdk#59]
For version 5.15.0

```
* com.mparticle:android-appboy-kit:5.15.0
  \-- com.appboy:android-sdk-ui:9.0.0
   \-- com.android.support:support-fragment:28.0.0
  \-- com.appboy:android-sdk-ui:9.0.0
   \-- com.android.support:recyclerview-v7:28.0.0
  \-- com.appboy:android-sdk-ui:9.0.0
   \-- com.android.support:support-core-ui:28.0.0
  \-- com.appboy:android-sdk-ui:9.0.0
   \-- com.android.support:support-core-utils:28.0.0
  \-- com.appboy:android-sdk-ui:9.0.0
   \-- com.android.support:support-compat:28.0.0
```

**Comment by willpassidomo** [comment]
Hey @brian-plummer-okcupid. I'm sorry, it seems like I overlooked your specific Appboy/Braze question in your last issue and gave you incomplete information. The `android-appboy-kit` was upgraded in version `5.15.3`, which was released about an hour ago, but has yet to land in Maven Central.

**Comment by brianPlummer** [comment]
@willpassidomo Thank you so much! That did the trick! :) I really appreciate it! :) :)
