### ISSUE TITLE
Crash when configuring the kit

### ISSUE THREAD

**Issue by ExpensiveBelly** [mParticle/mparticle-android-sdk#61]
mParticle version = 5.15.4
Android Operating System Version: 7.0
Brand: samsung
Model: Galaxy S6

Kits added: 
```
implementation "com.mparticle:android-core:$mParticleVersion"
implementation "com.mparticle:android-adjust-kit:$mParticleVersion"
implementation "com.mparticle:android-appboy-kit:$mParticleVersion"
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mparticle.identity.IdentityApi com.mparticle.MParticle.Identity()' on a null object reference
       at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:179)
       at com.mparticle.kits.KitManagerImpl$UpdateKitRunnable.run(KitManagerImpl.java:141)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by samdozor** [comment]
Hi @ExpensiveBelly thanks for logging this issue. Looks like this line:

https://github.com/mParticle/mparticle-android-sdk/blob/master/android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java#L179

That could only happen if somehow the mParticle singleton was destroyed. Are you by chancing calling [MParticle.reset() ](https://github.com/mParticle/mparticle-android-sdk/blob/master/android-core/src/main/java/com/mparticle/MParticle.java#L1085)anywhere in your code?  

Alternatively - can you make sure you're initializing MParticle (by calling MParticle.start()) on the main thread?

**Comment by ExpensiveBelly** [comment]
> Are you by chancing calling MParticle.reset() anywhere in your code?

Yes, we are

> Alternatively - can you make sure you're initializing MParticle (by calling MParticle.start()) on the main thread?

We are calling mParticle.start() on the main thread.

**Comment by willpassidomo** [comment]
Hey @ExpensiveBelly sorry this took us a while to get out. The usage of reset() preceding an NPE like this was something we had in the back of our heads as possible, but this pointed to a need to update our code in a number of places. Really appreciate you opening the Issue and this is fixed as of [this commit](https://github.com/mParticle/mparticle-android-sdk/commit/3fd3228f64b4a258482f87ab5a181f73b1a3ab8a) which is a part of release v5.15.6

**Comment by ExpensiveBelly** [comment]
Many thanks, we'll update the library.
