### ISSUE TITLE
Braze integration possibly out of date

### ISSUE THREAD

**Issue by mateot1** [mParticle/mparticle-android-sdk#63]
Hi, opening an issue here for visibility on another issue I already opened in the integration kit repo: https://github.com/mparticle-integrations/mparticle-android-integration-appboy/issues/45. 

At the very least, the documentation for this kit is out of date since `com.appboy.AppboyFcmReceiver` no longer exists. But I am wondering if there's possibly a bug since in order to get push notifications to display after updating from 5.15.1 to 5.16.5 I had to add a call directly to the Appboy sdk in our `FirebaseMessagingService` (`AppboyFirebaseMessagingService.handleBrazeRemoteMessage`). Should the `com.mparticle.MPService` that we added to our manifest be making this call instead? if not, do we still need this service declaration?

**Comment by alexs-mparticle** [comment]
@mateot1 Thanks for bringing this up. I'll have someone on our team look into this and get back to you when we have a resolution.

**Comment by mateot1** [comment]
I see now from https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/47 that the receiver was just renamed and not removed. We will continue using the renamed receiver, though it is a bit confusing if you consider Braze's changelog back for version [3.1.1](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#311):
> "Added AppboyFirebaseMessagingService to directly use the Firebase messaging event com.google.firebase.MESSAGING_EVENT. This is now the required way to integrate Firebase push with Braze. The AppboyFcmReceiver should be removed from your AndroidManifest and replaced with the following..."

**Comment by lmcjt37** [comment]
Is there any update around this?

I'm currently struggling with getting head's up notifications to show, the messages are always silent regardless of the "notification display priority".

From what I can tell, my app gets here https://github.com/Appboy/appboy-android-sdk/blob/91bbb0de3d8fe0e7616d0d86f7cc98eefef4ed61/android-sdk-ui/src/main/java/com/appboy/BrazePushReceiver.java#L136

But then never goes any further as I expect to see this log "Received notification push" from line 174 but it never comes and I think there is an error somewhere between

**Comment by willpassidomo** [comment]
Hey, we have updated the Appboy (Braze) Kit in version 5.20.0 to use their version 14.0. We're mulling over how we can migrate our own kit from `appboy-kit` to `braze-kit` in the future, but don't have any immediate plans for it.

@lmcjt37 it sounds like (if there is no other configuration error and the rest of the checks in the method you link pass) then you may be suffering from the same issues in the [comment above yours](https://github.com/mParticle/mparticle-android-sdk/issues/63#issuecomment-854055290). Our documentation has also been updated to reflect the change.
