### ISSUE TITLE
modify() requires a non-zero MPID, please make sure a MParticleUser is present before making a modify request

### ISSUE THREAD

**Issue by ericntd** [mParticle/mparticle-android-sdk#73]
Our app is crashing for some users and we see the following exception in logcat
```
2021-11-03 10:31:22.219 27133-27133/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 27133
    java.lang.IllegalArgumentException: modify() requires a non-zero MPID, please make sure a MParticleUser is present before making a modify request.
        at com.mparticle.identity.IdentityApi.modify(SourceFile:15)
        at com.myapp.feature.mparticle.MParticleManager.modifyIdentity(MParticleManager.java:90)
        at com.myapp.feature.authentication.AuthenticationManager.setCustomerIdForAnalyticsAfterLogIn(AuthenticationManager.java:413)
        at com.myapp.feature.authentication.AuthenticationManager$3.onReceiveSuccess(AuthenticationManager.java:381)
        at com.myapp.feature.authentication.AuthenticationManager$3.onReceiveSuccess(AuthenticationManager.java:355)
        at com.myapp.transport.OperationResultReceiver.onReceiveResult(OperationResultReceiver.java:32)
        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
Could this exception cause the crash?

**Comment by willpassidomo** [comment]
Hey @ericntd that is a definitely possibility, but we will only throw [this exception ](https://github.com/mParticle/mparticle-android-sdk/blob/38cf3fd635cc6fc0a11337f5c3bc29ca4748fbe6/android-core/src/main/java/com/mparticle/identity/IdentityApi.java#L265)when the app is in the development environment (when both environment is set as `Environment.Development` **and** the[ apk is debuggable](https://github.com/mParticle/mparticle-android-sdk/blob/38cf3fd635cc6fc0a11337f5c3bc29ca4748fbe6/android-core/src/main/java/com/mparticle/internal/MPUtility.java#L672)), the presence of the stack trace is leading me to think this is definitely not the error log, is it possible your users are using a debug build?

If that is the case, the exception could cause the app to crash. We would throw it on the same thread that `modify()` is called on, but again, that should only happen in development/debug builds

**Comment by ericntd** [comment]
Hi @willpassidomo , yes, you are right, this is definitely happening in development environment only!
My follow-up questions are:
1) Why does it only happens to some devices?
2) Why doesn't it end up in Crashlytics? We have our development environment wired up to Crashlytics too
3) What can we do about it? Our testers need the development environment for some test suites

**Comment by willpassidomo** [comment]
Ah, glad to hear that is working as expected!

This error will happen when the `currentUser` has not been set yet. We make an `Identity.identify()` call when MParticle starts, and Users are persisted, so this condition will only happen _before the initial identify call successfully completes_ for the first time (either after a new install or after a `MParticle.reset()` call)

We usually see a couple of general common cases that would trigger this:

1) you are calling `modify()` synchronously with `start()`, without waiting for the initial `identify()` request to return

either you could have some code like:
```
MParticleOptions options = MParticleOptions.builder(context)
    .... 
    ....
    .build()
MParticle.start(option);
MParticle.getInstance().Identity().modify(modifyRequest);
```

the better way to do this to avoid the error would be to only trigger the `modify()` call from with an `MParticleTask<IdentityApiResult>#onSuccess()` callback attached to `MParticleOptions`

a fix might looks like:

```
MParticleOptions options = MParticleOptions.builder(context)
    .identifyTask { newUser, previousUser -> 
        //move modify request logic here
        MParticle.getInstance().Identity().modify(modifyRequest);
    }
    .... 
    ....
    .build()
MParticle.start(option);
}


2) similar to above, but you have a trigger that kicks of the modify request that may be triggered before the initial `identify()` request returns. for example, if the modify call is tied to a button click like:

```
fun onClick(view: View) {
    MParticle.getInstance().Identity().modify(modifyRequest)
}
```

then you may need to gate that call with a check to see if the user is present, and attach to a global IdentityStateTransition listener if it is not. For example

```
fun onClick(view: View) {
    if (MParticle.getInstance().Identity().currentUser != null) {
        MParticle.getInstance().Identity().modify(modifyRequest)
    } else {
        MParticle.getInstance().Identity().addIdentityStateListener { newUser, previousUser -> 
        //this listener will continue to callback when the user changes so this logic will only pass the _first_ time a user is 
        //returned, otherwise `previousUser` will always be non-null. Alternativley, you can call `Identity().rermoveIdentityStateListener()` with a reference to your callback
        if (prerviousUser == null) {
            MParticle.getInstance().Identity().modify(modifyRequest)
        }
    }
}

```

3) The initial Identify request is failing for some unrecoverable reason. In this case, the fix in (2) will allow your app to keep running gracefully. If the timing bug described in (2) definitely doesn't apply, then a simple `if (currentUser != null)` will be fine on it's own

**Comment by willpassidomo** [comment]
to answer your other questions:

**Comment by ericntd** [comment]
Your 2nd solution works, thanks a lot @willpassidomo 👏 🙇
