### ISSUE TITLE
Question: what to do about MultipleInstallBroadcastReceiver onReceive ANR

### ISSUE THREAD

**Issue by ericntd** [mParticle/mparticle-android-sdk#77]
We have some ANR with AppsFlyer
[They recommend us to use SingleInstallBroadcastReceiver](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/29#issuecomment-975480207)
Would that work considering that we put most if not all of our AppsFlyer data through mParticle?

What do you think about the Install Referrer library?
https://developer.android.com/google/play/installreferrer/library

**Comment by einsteinx2** [comment]
@ericntd Apologies for the delayed response. I've routed this question to our Android team and will get a response for you ASAP and update this ticket.

**Comment by einsteinx2** [comment]
Closing this ticket, please re-open if you have further questions.
