### ISSUE TITLE
Leanplum kit 408 Errors

### ISSUE THREAD

**Issue by Turnsole** [mParticle/mparticle-android-sdk#99]
On a debug build the Leanplum kit errors out and fails to load dynamic variables. 

    D/[Leanplum][DEBUG]: Received start response: {}
    I/[Leanplum][INFO]: HTTP error 408 {"response":[{"success":false,"error":{"message":"Too Many Requests."}}]}

This is because they added a "Dev Mode Rate Limit" https://docs.leanplum.com/reference/responses to the Leanplum SDK.

**Comment by willpassidomo** [comment]
Hey @Turnsole. Unfortunately, we don't have any control over the internals of Leanplum and you would have to reach out to them to get modify this limit. On our side, it would be possible to reconfigure your integration to send the prod Leanplum key for development builds as well as production, but that really depends on whether your org is comfortable mixing that data in Leanplum.

Just to make sure I'm not missing anything, was there any kind of solution you were thinking of that we could implement on the Kit side?

**Comment by Turnsole** [comment]
I don't know how the Leanplum integration is set up by the mParticle SDK, but the only way I can see it working for debuggable builds again is either using some kind of rate limiter or not turning on dev mode (can you even do that?).

**Comment by willpassidomo** [comment]
Hey @Turnsole, sorry for my slow response. The mParticle SDK sends some basic information (environment, app version, available kits, etc) and the server returns a configuration for the kits, which would include a Leanplum API key in your case. In the mParticle dashboard, you likely configured a Leanplum debug key and a production key, so depending on the SDK's Environment state, the respective Leanplum key will be returned and used to initialize the Leanplum SDK.

So, the two potential workarounds you could use are **either:**
1) Set `MParticleOptions.Builder.environment(Environment.Production)` in your startup configuration. This may have some minor side effects, but is definitely the path of least resistance
2) Replace your debug/development Leanplum API key with the production on in the mParticle web app (so product key is returned for development builds)

Let me know if you run into issues with either approach, hopefully its just a simple fix :)
